import crypto from 'crypto';

export const RAZORPAY_KEY_ID =
  process.env.RAZORPAY_KEY_ID ||
  process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID ||
  'rzp_live_TgneYi4y1wFtMS';

export const RAZORPAY_KEY_SECRET =
  process.env.RAZORPAY_KEY_SECRET || 'hxgQBYqgXGAJ3mK1p6Ph9mhs';

export interface RazorpayOrderResponse {
  id: string;
  entity: string;
  amount: number;
  amount_paid: number;
  amount_due: number;
  currency: string;
  receipt: string;
  status: string;
  attempts: number;
  notes: Record<string, any>;
  created_at: number;
}

/**
 * Creates a Razorpay order via the official REST API.
 * @param amountInInr Price in Rupees (e.g. 299)
 * @param receipt Unique receipt ID (e.g. sub_123456)
 * @param notes Custom metadata attached to the order
 */
export async function createRazorpayOrder(
  amountInInr: number,
  receipt: string,
  notes?: Record<string, string>
): Promise<RazorpayOrderResponse> {
  const amountInPaise = Math.round(amountInInr * 100);

  const authHeader = `Basic ${Buffer.from(
    `${RAZORPAY_KEY_ID}:${RAZORPAY_KEY_SECRET}`
  ).toString('base64')}`;

  const response = await fetch('https://api.razorpay.com/v1/orders', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: authHeader,
    },
    body: JSON.stringify({
      amount: amountInPaise,
      currency: 'INR',
      receipt: receipt.slice(0, 40), // Razorpay limit: 40 chars
      notes: notes || {},
    }),
  });

  const data = await response.json();

  if (!response.ok) {
    console.error('Razorpay order creation failed:', data);
    throw new Error(data.error?.description || 'Failed to create Razorpay order');
  }

  return data as RazorpayOrderResponse;
}

/**
 * Validates the HMAC-SHA256 signature generated by Razorpay Checkout.
 */
export function verifyRazorpaySignature(
  orderId: string,
  paymentId: string,
  signature: string
): boolean {
  if (!orderId || !paymentId || !signature) return false;

  const expectedSignature = crypto
    .createHmac('sha256', RAZORPAY_KEY_SECRET)
    .update(`${orderId}|${paymentId}`)
    .digest('hex');

  return expectedSignature === signature;
}
